let Idiomas = {
  "AA": "Afar",
  "AB": "Abkhazian",
  "AE": "American Eskimo",
  "AF": "Anglo-French",
  "AL": "All Languages",
  "AM": "Amharic",
  "AR": "Arabic",
  "AS": "Assamese",
  "AY": "Aymara",
  "AZ": "Azerbaijani",
  "BA": "Bashkir",
  "BE": "Byelorussian",
  "BG": "Bulgarian",
  "BH": "Bihari",
  "BI": "Bislama",
  "BN": "Bengali",
  "BO": "Tibetan",
  "BP": "Brazilian Portuguese",
  "BR": "Breton",
  "CA": "Catalan",
  "CF": "Canadian French",
  "CH": "Colloquial Hebrew",
  "CO": "Corsican",
  "CR": "Czech Republic",
  "CS": "Czech",
  "CY": "Welsh",
  "DE": "DEutsch (German)",
  "DR": "Dominican Republic",
  "DT": "Deutsch (German)",
  "DZ": "Bhutani",
  "EF": "English French",
  "EG": "English German",
  "EJ": "English Japanese",
  "EL": "Greek",
  "EN": "English",
  "EO": "Esperanto",
  "EP": "European Portuguese",
  "ER": "English Russian",
  "ES": "Spanish",
  "ET": "Estonian",
  "EU": "Basque",
  "FA": "Farsi (Persian)",
  "FE": "Foreignish English",
  "FI": "Finnish",
  "FJ": "Fiji",
  "FO": "Faroese",
  "FR": "French",
  "FY": "Frisian",
  "GA": "Gaelic (Irish)",
  "GD": "Scots Gaelic",
  "GL": "Great Lakes (USA)",
  "GN": "Guarani",
  "GU": "Gujarati",
  "HA": "Hausa",
  "HE": "Hebrew",
  "HI": "Hindi",
  "HR": "Croatian",
  "HU": "Hungarian",
  "HY": "Armenian",
  "IA": "Interlingua",
  "IE": "Interlingue",
  "IK": "Inupiak",
  "IL": "Illinois",
  "IN": "Indonesian",
  "IS": "Icelandic",
  "IT": "Italian",
  "IW": "Hebrew",
  "JA": "Japanese",
  "JI": "Yiddish",
  "JV": "Javanese",
  "KA": "Georgian",
  "KK": "Kazakh",
  "KL": "Greenlandic",
  "KM": "Cambodian",
  "KN": "Kannada",
  "KO": "Korean",
  "KS": "Kashmiri",
  "KU": "Kurdish",
  "KY": "Kirghiz",
  "LA": "Latin",
  "LN": "Lingala",
  "LO": "Laothian",
  "LS": "Los Santos",
  "LT": "Lithuanian",
  "LV": "Latvian",
  "MG": "Malagasy",
  "MI": "Maori",
  "MK": "Macedonian",
  "ML": "Malayalam",
  "MN": "Mongolian",
  "MO": "Moldavian",
  "MR": "Marathi",
  "MS": "Malay",
  "MT": "Maltese",
  "MY": "Burmese",
  "NA": "Nauru",
  "ND": "New Delhi",
  "NE": "Nepali",
  "NL": "Dutch (Netherlands)",
  "NO": "Norwegian",
  "NT": "New Taiwanese",
  "OC": "Occitan",
  "OF": "Old French",
  "OG": "Original German",
  "OM": "Afan (Oromo)",
  "OR": "Oriya",
  "PA": "Punjabi",
  "PL": "Polish",
  "PN": "Pitcairn",
  "PS": "Pashto",
  "PT": "Portuguese",
  "QU": "Quechua",
  "RE": "Russian English",
  "RM": "Rhaeto-Romance",
  "RN": "Kurundi",
  "RO": "Romanian",
  "RU": "Russian",
  "RW": "Kinyarwanda",
  "SA": "Sanskrit",
  "SC": "Sardinian",
  "SD": "Sindhi",
  "SF": "Sentence Fragment",
  "SG": "Sangho",
  "SH": "Serbo-croatian",
  "SI": "Sino Indian",
  "SK": "Slovak",
  "SL": "Slovenian/Slovene",
  "SM": "Samoan",
  "SN": "Shona",
  "SO": "Somali",
  "SQ": "Albanian",
  "SR": "Serbian",
  "SS": "Siswati",
  "ST": "Sesotho",
  "SU": "Sundanese",
  "SV": "Swedish",
  "SW": "Swahili",
  "TA": "Tamil",
  "TE": "Telugu",
  "TG": "Tajik",
  "TH": "Thai",
  "TI": "Tigrinya",
  "TJ": "Total Jive",
  "TK": "Turkmen",
  "TL": "Tagalog",
  "TN": "Tennessee",
  "TO": "Tonga",
  "TP": "Timor Portuguese",
  "TR": "Turkish",
  "TS": "Tsonga",
  "TT": "Tatar",
  "TW": "Twi",
  "UK": "Ukrainian",
  "UL": "Uppaal Language",
  "UR": "Urdu",
  "UZ": "Uzbek",
  "VI": "Vietnamese",
  "VO": "Volapuk",
  "WO": "Wolof",
  "XH": "Xhosa",
  "YO": "Yoruba",
  "ZG": "Zagreb (Croatia)",
  "ZH": "Chinese",
  "ZU": "Zulu"
};

export { Idiomas as Idiomas };